In [1]:
%matplotlib inline

In [2]:
import numpy as np

# Transitioning form MatLab to Python - Arrays
Transitioning from using MatLab to using Python can be daunting at first. However, many of the methods available in MatLab have rewritten in python. This notebook will explore the equivalencies between these two languages.

## Contents
- [Array Creation](#Array-Creation)
- [Array Concatenation](#Array-Concatenation)
- [Array Slicing](#Array-Slicing)

### Array Creation

<table>
   <tr>
      <th>Example</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MatLab&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Python&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Output&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
   </tr>
   <tr>
      <td>1</td>
      <td>a = [1, 2, 3, 4]</td>
      <td>b = np.array([1,2,3,4])</td>
      <td>[1 2 3 4]</td>
   </tr>
   <tr>
      <td>2</td>
      <td>b = linspace(1, 4, 2)</td>
      <td>b = np.linspace(1, 4, 2)</td>
      <td>[1 4]</td>
   </tr>
   <tr>
      <td>3</td>
      <td>c = zeros(2)</td>
      <td>c = np.zeros(2)</td>
      <td>[0 0]</td>
   </tr>
   <tr>
      <td>4</td>
      <td>d = rand(2)</td>
      <td>d = np.random.rand(2)</td>
      <td>[* *]</td>
   </tr>
   <tr>
      <td>5</td>
      <td>e = eye(3)</td>
      <td>e = np.random.rand(2)</td>
      <td>[[1 0 0]<br>[0 1 0]<br>[0 0 1]]</td>
   </tr>
   <tr>
      <td>6</td>
      <td>f = diag([1 2 3])</td>
      <td>f = np.diag([1, 2, 3])</td>
      <td>[[1 0 0]<br>[0 2 0]<br>[0 0 3]]</td>
   </tr>
</table>

In [6]:
## Example 1
a = np.array([1,2,3,4])
print("Example 1:", a)

## Example 2
b = np.linspace(1, 4, 2)
print("Example 2:", b)

## Example 3
c = np.zeros(2)
print("Example 3:", c)

## Example 4
d = np.random.rand(2)
print("Example 4:", d)

## Example 5
e = np.identity(3)
print("Example 5:\n", e)

## Example 6
f = np.diag([1, 2, 3])
print("Example 6:\n", f)

Example 1: [1 2 3 4]
Example 2: [1. 4.]
Example 3: [0. 0.]
Example 4: [0.64483871 0.13900165]
Example 5:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Example 6:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


### Array Concatenation

Concatenation in python is similar to the `cat` method in MatLab. Note: The indexing for axes begins at 0 rather than 1.

<table>
   <tr>
      <th>Example</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MatLab&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Python&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Output&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
   </tr>
   <tr>
      <td>1</td>
      <td>a1 = ones(3)<br>a2 = zeros(3)<br>a = cat(1, a1, a2)</td>
      <td>a1 = np.ones((3, 3))<br>a2 = np.zeros((3, 3))<br>a = np.concatenate((a1, a2), axis=0)</td>
      <td>[[1 1 1]<br>
 [1 1 1]<br>
 [1 1 1]<br>
 [0 0 0]<br>
 [0 0 0]<br>
 [0 0 0]]</td>
   </tr>
    <tr>
      <td>2</td>
      <td>b1 = ones(3)<br>b2 = zeros(3)<br>b = cat(2, b1, b2)</td>
      <td>b1 = np.ones((3, 3))<br>b2 = np.zeros((3, 3))<br>b = np.concatenate((b1, b2), axis=1)</td>
      <td> [[1 1 1 0 0 0]<br>
 [1 1 1 0 0 0]<br>
 [1 1 1 0 0 0]]</td>
   </tr>
</table>

In [7]:
## Example 1
a1 = np.ones((3, 3))
a2 = np.zeros((3, 3))
a = np.concatenate((a1, a2), axis=0)
print("Example 1:\n", a)

## Example 2
b1 = np.ones((3, 3))
b2 = np.zeros((3, 3))
b = np.concatenate((b1, b2), axis=1)
print("Example 2:\n", b)

Example 1:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Example 2:
 [[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


### Array Slicing

<table>
   <tr>
      <th>Example</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MatLab&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Python&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Output&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
   </tr>
   <tr>
      <td>1</td>
      <td>a1 = [16 5 9 4 2 11 7 14]<br> a = a1(1:2:end)</td>
      <td>a1 = np.array([16 5 9 4 2 11 7 14])<br> a = a1[2:7]</td>
      <td>[ 9  4  2 11  7]</td>
   </tr>
    <tr>
      <td>2</td>
      <td>b1 = [16 5 9 4 2 11 7 14]<br> b = b1(1:2:end)</td>
      <td>b1 = np.array([16 5 9 4 2 11 7 14])<br> b = b1[::2]</td>
        <td>[16  9  2  7]</td>
   </tr>
    <tr>
      <td>3</td>
      <td>c1 = [16 5 9 4 2 11 7 14]<br> c = c1(end:-1:1) </td>
      <td>c1 = np.array([16 5 9 4 2 11 7 14])<br> c = c1[::-1]</td>
        <td>[14  7 11  2  4  9  5 16]</td>
   </tr>
</table>