In [1]:
%matplotlib inline

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
x = np.array([1,2,3,4])
print(x)
y = np.arange(0,10,2)
print(y)

[1 2 3 4]
[0 2 4 6 8]


In [13]:
# slicing
x = np.arange(1,20)
print(x)
x[0:20:2]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [10]:
x[0:-5]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
x[-1:-5:-1]

array([19, 18, 17, 16])

In [16]:
# nifty way to reverse an array - not specifying an index is a way of saying go to the end
x[-1::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1])